########################################
# Personal Preferences

# It's ok to add some spaces between stuff to make it more readable!
Layout/TrailingEmptyLines:
  Enabled: false

# Personal preference (we don't find `json, = Open3.capture3(…)` with the `x, = ` syntax super readable)
Style/TrailingUnderscoreVariable:
  Enabled: false

########################################
# Some specific files exceptions

# podspecs are ruby with a special extension
Naming/FileName:
  Exclude:
    - '*.podspec'

# Rake uses `task :x => [deps]`, we don't want to convert it to `task x: [deps]`
# Podfile also has specific DSL so it's ok to not be strict about Hash syntax there
Style/HashSyntax:
  Exclude:
    - 'Podfile'
    - 'Rakefile'
    - 'rakelib/*.rake'

# Danger uses `fail` as a keyword, we don't want rubocop to replace it with `raise`
Style/SignalException:
  Exclude:
    - 'Dangerfile'

########################################
# Metrics

Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Max: 180

Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

########################################

# Enable new cops of recent rucocop updates by default
AllCops:
  NewCops: enable
